---
sudo: required
dist: trusty

env:
  # Debian 8 (jessie)
  - IMAGE="images:debian/jessie" ODOO_VERSIONS="8.0 9.0 10.0" ODOO_INSTALL_TYPES="standard buildout pip" ANSIBLE_VERSION="2.4,<2.5"
  # Debian 9 (stretch)
  - IMAGE="images:debian/stretch" ODOO_VERSIONS="8.0 9.0 10.0 11.0" ODOO_INSTALL_TYPES="standard buildout pip" ANSIBLE_VERSION="2.4,<2.5"
  # Ubuntu 14.04 (trusty)
  - IMAGE="ubuntu:trusty" ODOO_VERSIONS="8.0 9.0 10.0" ODOO_INSTALL_TYPES="standard buildout pip" ANSIBLE_VERSION="2.4,<2.5"
  # Ubuntu 16.04 (xenial)
  - IMAGE="ubuntu:xenial" ODOO_VERSIONS="8.0 9.0 10.0 11.0" ODOO_INSTALL_TYPES="standard buildout pip" ANSIBLE_VERSION="2.4,<2.5"

install:
  # Spawn multiple LXD container
  - sudo ./tests/travis_lxd/install.sh
  - sudo ./tests/travis_lxd/set_storage_pool_ramdisk.sh
  - sudo ./tests/travis_lxd/create_base_container.sh odoo-test

script:
  # Test the project into these containers
  - sudo ./tests/travis_lxd/run_tests_in_container.sh odoo-test
